name = "code-x-landing"
compatibility_date = "2024-01-15"
pages_build_output_dir = "out"

# Production environment configuration
[env.production]
name = "code-x-landing"

[env.preview]
name = "code-x-landing-preview"

# Build command is configured in Cloudflare Pages dashboard
# Command: npm run pages:build
# Output directory: out

# Environment variables (add your secrets here)
# [env.production.vars]
# NEXT_PUBLIC_ANALYTICS_ID = "your-analytics-id"

# Custom domains configuration
[[routes]]
pattern = "code-x.app/*"
zone_name = "code-x.app"
