# Cloudflare Pages-friendly configuration
compatibility_date = "2024-01-15"

[pages]
# Where Next.js static export outputs the files
pages_build_output_dir = "out"
# This configuration is optimized for Pages deployment
# Last updated: 2024-09-23

# Build settings are configured in Cloudflare Pages dashboard:
# Build command: npm run pages:build
# Build output directory: out
# Custom domain: code-x.app

# Optional bindings for Pages Functions (if needed later):
# [[kv_namespaces]]
# binding = "FORM_SIGNUPS"
# id = "xxxxxx"

# [[d1_databases]]
# binding = "DB"
# database_name = "code_x"
# database_id = "xxxxxx"

# [[r2_buckets]]
# binding = "ASSETS"
# bucket_name = "code-x-assets"
